//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teko.Model
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    public partial class Contenidos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Profesor { get; set; }
        public int Cursada { get; set; }
        public string UsuariosId { get; set; }
        public Nullable<int> EscuelasId { get; set; }
        public Nullable<int> MateriasId { get; set; }
        public Nullable<int> TiposContenidosId { get; set; }
        public Nullable<int> IPop { get; set; }
        public Nullable<int> IDes { get; set; }
        public Nullable<System.DateTime> FechaSubida { get; set; }
        public string Badget { get; set; }
        public double ValoracionPromedio { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Escuelas Escuelas { get; set; }
        public virtual Materias Materias { get; set; }
        public virtual TiposContenidos TiposContenidos { get; set; }

        public virtual ICollection<Archivos> Archivos { get; set; }
       
        public bool IsDeleted { get; set; }

    }
}
